name: NuGet Publish

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
    - name: Publish Chores
      uses: Ran-doo/GitHub-WorkFlows/.github/steps/setup_core@main
      with:
        token: ${{ secrets.GithubPackages_Key }}