name: NuGet Publish

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
    - name: Pulish action
      uses: actions/checkout@v4
      with:
        repository: "GitHub-WorkFlows"
        ref: 'main'
        token: ${{ secrets.GithubPackages_Key }}

    - name: Publish Chores
      uses: "./GitHub-WorkFlows/.github/steps/setup_core"
      with:
        token: ${{ secrets.GithubPackages_Key }}