name: NuGet Publish

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
    - name: Clone Actions Repo
      shell: bash
      run: |
        git clone https://${{ secrets.GithubPackages_Key }}@github.com/Ran-doo/GitHub-WorkFlows

    - name: Publish Chores
      uses: "./GitHub-WorkFlows/.github/steps/package_publish"
      with:
        token: ${{ secrets.GithubPackages_Key }}
        repo_name: "SimpleShimmer"
        nuget_token: ${{ secrets.Nu_Key }}